
IF(WIN32)
    message("Checking gstreamer")
    #=======================
    find_path(GSTREAMER_INCLUDE_DIR_FOUND gst.h ${GSTREAMER_INCLUDE_DIR}/gst)
    find_path(GSTREAMER_LIB_DIR_FOUND gstreamer.lib ${GSTREAMER_LIB_DIR})
    
    if(GSTREAMER_INCLUDE_DIR_FOUND AND GSTREAMER_LIB_DIR_FOUND)
        set(GSTREAMER_INCLUDE_DIRS "${GSTREAMER_INCLUDE_DIR}" " ${LIBXML2_INCLUDE_DIR}")
        set(GSTREAMER_LIBRARIES gstreamer.lib gstfarsight.lib xml2.lib gstinterfaces.lib)
        set(GSTREAMER_LIB_DIRS ${GSTREAMER_LIB_DIR})
        message("GSTREAMER configured")
        set(GSTREAMER_FOUND TRUE)
    else(GSTREAMER_INCLUDE_DIR_FOUND AND GSTREAMER_LIB_DIR_FOUND)
        set(GSTREAMER_FOUND FALSE)
        message(${GSTREAMER_INCLUDE_DIR_FOUND})
        message(${GSTREAMER_LIB_DIR_FOUND})
        message(FATAL_ERROR "GSTREAMER not found -> config fails")
    endif(GSTREAMER_INCLUDE_DIR_FOUND AND GSTREAMER_LIB_DIR_FOUND)
ENDIF(WIN32)