

message("check-tp-farsight.cmake")


if(WIN32)
    message("Checking tp-farsight")
    find_path(TELEPATHY_FARSIGHT_INCLUDE_DIR_FOUND channel.h ${TELEPATHY_FARSIGHT_INCLUDE_DIR}/telepathy-farsight/)
    find_path(TELEPATHY_FARSIGHT_LIB_DIR_FOUND telepathy-farsight.lib ${TELEPATHY_FARSIGHT_LIB_DIR} ${TELEPATHY_FARSIGHT_LIB_DIR}/Release/ ${TELEPATHY_FARSIGHT_LIB_DIR}/Debug/)

    if(TELEPATHY_FARSIGHT_INCLUDE_DIR_FOUND AND TELEPATHY_FARSIGHT_LIB_DIR_FOUND)
        set(TELEPATHY_FARSIGHT_INCLUDE_DIRS "${TELEPATHY_FARSIGHT_INCLUDE_DIR}")
        set(TELEPATHY_FARSIGHT_LIBRARIES telepathy-farsight.lib)
        set(TELEPATHY_FARSIGHT_LIB_DIRS ${TELEPATHY_FARSIGHT_LIB_DIR}/ ${TELEPATHY_FARSIGHT_LIB_DIR}/Release/ ${TELEPATHY_FARSIGHT_LIB_DIR}/Debug/)
        message("telepathy-farsight configured")
        set(TP_FARSIGHT_FOUND 1)
    else(TELEPATHY_FARSIGHT_INCLUDE_DIR_FOUND AND TELEPATHY_FARSIGHT_LIB_DIR_FOUND)
        set(TP_FARSIGHT_FOUND 0)
        message(${TELEPATHY_FARSIGHT_INCLUDE_DIR_FOUND})
        message(${TELEPATHY_FARSIGHT_LIB_DIR_FOUND})
        message(FATAL_ERROR "telepathy farsight not found -> config fails")
    endif(TELEPATHY_FARSIGHT_INCLUDE_DIR_FOUND AND TELEPATHY_FARSIGHT_LIB_DIR_FOUND)
    
    
ENDIF(WIN32)